ISC-MakeIT/rackle

src/components/mapComponents/CustomMap.ts
src/components/mapComponents/MapViewComponent.tsx

カスタムマップを使って駅周辺のいらないものを削除
インドアマップに対応していないのか駅内のアイコン消せませんでした

カスタムマップを使用

---

package.json
yarn.lock

package.jsonにreact-native-extended-stylesheetを追記し忘れたままmergeしてしまったこと

add EStyleSheet to package.json

---

src/components/movieComponents/MovieNavigateComponent.tsx
src/components/movieComponents/SubMovieComponent.tsx
src/screens/GuideScreen.tsx

- 小窓にて動画を流すのではなく、サムネを出すというぽいので一旦こんな感じ

Fix layout guide screen sub window

---

src/constants/Colors.ts
src/screens/GuideScreen.tsx
src/screens/HomeScreen.tsx

HomeとGuideのCSSを％対応したり調整したりした

---

src/components/NavigationPlate.tsx
src/components/StyledText.tsx
src/components/TabBarIcon.tsx
src/components/movieComponents/MovieNavigateComponent.tsx
src/components/movieComponents/SubMovieComponent.tsx
src/screens/GuideScreen.tsx
src/screens/MyPageScreen.tsx

- SFC -> FC 
- GuideScreenのState周りとか調整

ざっくりRefactor

---

src/components/movieComponents/ControlBarComponent.tsx
src/components/movieComponents/MovieNavigateComponent.tsx
src/components/movieComponents/ThumbnailListComponent.tsx

Refactor movie

---

src/components/Modal.tsx
src/components/mapComponents/MapViewComponent.tsx
src/components/mapComponents/MarkerComponent.tsx
src/domains/gate.ts
src/domains/map.ts
src/dummydata/mapData.ts
src/screens/GuideScreen.tsx

WIP: Link of marker

---

src/domains/station.ts
src/screens/HomeScreen.tsx
src/services/client.ts
src/services/gates.ts
src/services/stations.ts
src/services/train_lines.ts

Use api for home screen

---

src/components/NavigationPlate.tsx
src/components/movieComponents/MovieNavigateComponent.tsx
src/navigation/MainTabNavigator.tsx
src/screens/GuideScreen.tsx
yarn.lock

モーダルが下から上に　ぴゅい　っと出てきます。
再生バーについてはカンプ通りにできなかったです。
ライブラリ依存なので改修が多くなると見込みスルーです。

再生ボタンを押すと動画モーダルが表示されます

---

src/components/StyledText.tsx
src/screens/GuideScreen.tsx

カルーセルにサムネイルが表示されます。
ぷらすあるふぁでstyledtextと変数名の修正。

【ブランチ名違い】サムネイル画像を表示するようにしちゃいました。

---

src/screens/GuideScreen.tsx

カルーセル1つめのサムネイルが表示できないため急ごしらえのバグ対応。
今日が終わったら即直しましょう。

動的にサムネイルを切り替える機能の実装

---

src/navigation/AppNavigator.ts
src/navigation/MainTabNavigator.tsx

:shower: remove tabNavigator

---

src/App.tsx
src/components/mapComponents/MapViewComponent.tsx
src/components/mapComponents/MarkerComponent.tsx
src/components/movieComponents/MovieNavigateComponent.tsx
src/domains/gate.ts
src/domains/location_point.ts
src/domains/map.ts
src/domains/movie.ts
src/domains/object_point.ts
src/screens/GuideScreen.tsx

やったこと
- DB変更に対応
- MarkerComponent.tsxのリファクタ
まだやっていないところ
- カルーセル周りのバグ

Map api modification

---

src/screens/GuideScreen.tsx

カルーセルの下にあるポチポチをいい感じにした

---

src/screens/GuideScreen.tsx

:+1: GuideScreenに戻るボタンを設置

---

src/components/Modal.tsx
src/components/mapComponents/MapViewComponent.tsx
src/components/mapComponents/MarkerComponent.tsx
src/screens/GuideScreen.tsx

やったこと
- カルーセル表示中にマップクリックでカルーセルを非表示に
- 画像をs3のやつを使って表示
やってないこと
- カルーセルがエレベーターの時に表示する左上の何人乗りかの表示
- 動画は手つけていない

Carousel modification

---

package.json
src/components/movieComponents/MovieNavigateComponent.tsx
src/screens/GuideScreen.tsx
yarn.lock

\@expo/videoplayerにブランチ切って作成。
git upgrade \@expo/videoplayer して受け取ってください。
追記 yarn install でも可

1タップで再生・停止の切り替え

---

src/components/mapComponents/MapViewComponent.tsx
src/screens/GuideScreen.tsx

やったこと
- カルーセルの初回表示時にcarouselMarkerがundefinedになるバグ修正
- カルーセルを閉じたときにマップを少し下にずらすように変更

カルーセル周りのバグ修正

---

src/screens/HomeScreen.tsx

最初の画面の背景画像の表示を調整

---

src/components/mapComponents/MapViewComponent.tsx
src/screens/GuideScreen.tsx
tslint.json

Refactor guide screen

---

src/App.tsx
src/components/Modal.tsx
src/screens/GuideScreen.tsx

Carousel correction
